table aux_month_numbers
	lineageTag: d48d5442-2fc4-43ea-b092-949b2d2841b0

	column month
		dataType: string
		lineageTag: 6c474ba0-4d14-4bb1-b41d-685f8f895ee3
		summarizeBy: none
		sourceColumn: month

		annotation SummarizationSetBy = Automatic

	column index
		dataType: string
		lineageTag: 49ebc838-2ae4-4c20-b756-995179696587
		summarizeBy: none
		sourceColumn: index

		annotation SummarizationSetBy = Automatic

	partition aux_month_numbers = m
		mode: import
		queryGroup: aux_tables
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("Rc5NDsIgEIbhu8y6i6LW1mWLo8HwYyiYVNL7X6PwQXT5vDOESYnYsnfUUS9o7xI9ePEtnBDM7L/gGZwXr3ThpU03DAfoFa0Cr426cqxPn24N8ASv/A6KTf6vtBuakyHWIHoE6z6/HVFPvCv5T/nI/QA=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [month = _t, index = _t])
				in
				    Source

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

