table calendar
	lineageTag: a0aadf48-e0ea-4234-b450-9e33dd3dfe3e

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 2f8f8664-7c2d-47b1-9c36-aa846ba98820
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: 6b80ebe5-de9b-4fb2-b716-91c682cf0b1d
			defaultHierarchy: LocalDateTable_446f9230-5d24-4b82-9da3-41edb1ff396a.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 1e78af6a-2988-4317-8375-d9c282a1ae26
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column 'Start of year'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 4489fc6d-ea30-4646-a7e2-3949e2325957
		summarizeBy: none
		sourceColumn: Start of year

		variation Variation
			isDefault
			relationship: 6d535819-a303-437d-9a05-89018edc8c47
			defaultHierarchy: LocalDateTable_d00ca0d3-8ef4-4ec4-99e7-00194def45c7.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'End of year'
		dataType: dateTime
		formatString: Long Date
		lineageTag: eb6ad151-759f-407e-be4c-ba3b273c9daa
		summarizeBy: none
		sourceColumn: End of year

		variation Variation
			isDefault
			relationship: d83e0ff1-4fe4-4a36-bad6-b06323a15740
			defaultHierarchy: LocalDateTable_a633a5d0-81f4-46e9-9418-df5ee7f634a1.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Quarter
		dataType: double
		lineageTag: 5e2a028a-e5bd-4fb2-a2bc-3e0e4de8c78b
		summarizeBy: sum
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Qtr
		dataType: string
		lineageTag: a38ee3da-9162-4f03-87dd-385f0d603839
		summarizeBy: none
		sourceColumn: Qtr

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: double
		lineageTag: c12758e3-2472-49ff-b875-6a4bc98cc3c6
		summarizeBy: sum
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Month name'
		dataType: string
		lineageTag: 43ef1344-ef5c-4581-b871-29db81c31b8b
		summarizeBy: none
		sourceColumn: Month name

		annotation SummarizationSetBy = Automatic

	column 'Days in month'
		dataType: double
		lineageTag: 2a52c07a-64e5-4b59-b3a5-a69ab9bf35d5
		summarizeBy: sum
		sourceColumn: Days in month

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Week of year'
		dataType: double
		lineageTag: 23c87d94-5c2f-4959-895a-1b9a305a4313
		summarizeBy: sum
		sourceColumn: Week of year

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Start of week'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 06e9ca3b-98fb-4d5e-a5ad-3ffb0c53a423
		summarizeBy: none
		sourceColumn: Start of week

		variation Variation
			isDefault
			relationship: e2aaabf4-404d-44ac-bd9f-6a790bd2b55a
			defaultHierarchy: LocalDateTable_f3c53213-6751-4d96-bec9-b105d1d39da0.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Day name'
		dataType: string
		lineageTag: 211abaf5-e2b7-44ff-be27-3c38548e0b3d
		summarizeBy: none
		sourceColumn: Day name

		annotation SummarizationSetBy = Automatic

	column 'Day of year'
		dataType: double
		lineageTag: e6b5f23d-9256-4375-909c-cef2a0ff8877
		summarizeBy: sum
		sourceColumn: Day of year

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Day of week'
		dataType: double
		lineageTag: 6ad62d6e-9f57-4cdd-9aaa-33e4c1884621
		summarizeBy: sum
		sourceColumn: Day of week

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column YYYYMMDD
		dataType: int64
		formatString: 0
		lineageTag: 64f5611e-85b9-462a-b553-5afa73339310
		summarizeBy: sum
		sourceColumn: YYYYMMDD

		annotation SummarizationSetBy = Automatic

	column YYYYMM
		dataType: int64
		formatString: 0
		lineageTag: e055c0fb-98fc-420c-8619-38fac3381837
		summarizeBy: none
		sourceColumn: YYYYMM

		annotation SummarizationSetBy = Automatic

	column 'Year Month Abrev'
		dataType: string
		lineageTag: 123441ec-a294-422a-9427-863705d2e1e8
		summarizeBy: none
		sourceColumn: Year Month Abrev

		annotation SummarizationSetBy = Automatic

	column ano_mes_semana
		dataType: string
		lineageTag: 0ac84220-4f61-4628-bd52-6a3b581b6278
		summarizeBy: none
		sourceColumn: ano_mes_semana

		annotation SummarizationSetBy = Automatic

	column 'Week of Month'
		dataType: string
		lineageTag: c14ac147-b0e5-454b-aee3-33db14460749
		summarizeBy: none
		sourceColumn: Week of Month

		annotation SummarizationSetBy = Automatic

	partition calendar = m
		mode: import
		source =
				let
				    Source = List.Dates(#date(2022,1,1), 1800, #duration(1, 0, 0, 0)),
				    #"Converted to Table" = Table.FromList(
				    Source,
				    Splitter.SplitByNothing(),
				    null,
				    null,
				    ExtraValues.Error
				    ),
				    #"Renamed Columns" = Table.RenameColumns(#"Converted to Table", {{"Column1", "Date"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns", {{"Date", type date}}),
				    #"Inserted Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Inserted start of year" = Table.AddColumn(
				    #"Inserted Year",
				    "Start of year",
				    each Date.StartOfYear([Date]),
				    type nullable date
				    ),
				    #"Inserted end of year" = Table.AddColumn(
				    #"Inserted start of year",
				    "End of year",
				    each Date.EndOfYear([Start of year]),
				    type nullable date
				    ),
				    #"Inserted quarter" = Table.AddColumn(
				    #"Inserted end of year",
				    "Quarter",
				    each Date.QuarterOfYear([Date]),
				    type nullable number
				    ),
				    #"Inserted Merged Column" = Table.AddColumn(
				    #"Inserted quarter",
				    "Qtr",
				    each Text.Combine({"Q", Text.From([Quarter], "en-US")}),
				    type text
				    ),
				    #"Inserted month" = Table.AddColumn(
				    #"Inserted Merged Column",
				    "Month",
				    each Date.Month([Date]),
				    type nullable number
				    ),
				    #"Inserted month name" = Table.AddColumn(
				    #"Inserted month",
				    "Month name",
				    each Date.MonthName([Date]),
				    type nullable text
				    ),
				    #"Inserted days in month" = Table.AddColumn(
				    #"Inserted month name",
				    "Days in month",
				    each Date.DaysInMonth([Date]),
				    type nullable number
				    ),
				    #"Inserted week of year" = Table.AddColumn(
				    #"Inserted days in month",
				    "Week of year",
				    each Date.WeekOfYear([Date]),
				    type nullable number
				    ),
				    #"Inserted start of week" = Table.AddColumn(
				    #"Inserted week of year",
				    "Start of week",
				    each Date.StartOfWeek([Date]),
				    type nullable date
				    ),
				    #"Inserted day name" = Table.AddColumn(
				    #"Inserted start of week",
				    "Day name",
				    each Date.DayOfWeekName([Date]),
				    type nullable text
				    ),
				    #"Inserted day of year" = Table.AddColumn(
				    #"Inserted day name",
				    "Day of year",
				    each Date.DayOfYear([Date]),
				    type nullable number
				    ),
				    #"Inserted day of week" = Table.AddColumn(
				    #"Inserted day of year",
				    "Day of week",
				    each Date.DayOfWeek(([Date]), Day.Monday) + 1,
				    type nullable number
				    ),
				    #"Added sk_fecha" = Table.TransformColumnTypes(Table.AddColumn(#"Inserted day of week", "YYYYMMDD", each Date.ToText([Date], [Format = "yyyyMMdd"])), {{"YYYYMMDD", Int64.Type}}),
				    #"Added sk_ano_mes" = Table.TransformColumnTypes(Table.AddColumn(#"Added sk_fecha", "YYYYMM", each Date.ToText([Date], [Format = "yyyyMM"])), {{"YYYYMM", Int64.Type}}),
				    #"Added Month Abrev" = Table.TransformColumnTypes(Table.AddColumn(#"Added sk_ano_mes", "Year Month Abrev", each Number.ToText([Year]) & " - " & Text.Start([Month name], 3)), {{"Year Month Abrev", type text}}),
				    #"Added ano_mes_semana" = Table.TransformColumnTypes(Table.AddColumn(#"Added Month Abrev", "ano_mes_semana", each Number.ToText([Year]) & "-" & Number.ToText([Month]) & "-W" & Number.ToText(Date.WeekOfMonth([Date]))), {{"ano_mes_semana", type text}}),
				    #"Added Week of Month" = Table.TransformColumnTypes(Table.AddColumn(#"Added ano_mes_semana", "Week of Month", each "W" & Number.ToText(Date.WeekOfMonth([Date]))), {{"Week of Month", type text}})
				in
				    #"Added Week of Month"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

