table monthly_usdt_exchange_rate
	lineageTag: 67211bf2-d0d9-4a64-a842-102218aac4b3

	column YYYYMM
		dataType: int64
		formatString: 0
		lineageTag: df0636f2-1fda-48af-9c45-64135001c2c8
		summarizeBy: none
		sourceColumn: YYYYMM

		annotation SummarizationSetBy = Automatic

	column prices
		dataType: double
		lineageTag: c22fdd21-ac1b-4230-b033-f551b02de316
		summarizeBy: none
		sourceColumn: prices

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition monthly_usdt_exchange_rate = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("Z:\Code\07_usdc_analyzer\data\clean_usdt_bob_monthly_price_history.xlsx"), null, true),
				    Sheet1_Sheet = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"YYYYMM", Int64.Type}, {"prices", type number}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

