table word_count
	lineageTag: c8e7507d-722b-4c70-9b2e-3b5445672ac7

	column clean_title
		dataType: string
		lineageTag: a7138e8e-e7ec-46df-8541-923579bd8bd0
		summarizeBy: none
		sourceColumn: clean_title

		annotation SummarizationSetBy = Automatic

	column Count
		dataType: int64
		formatString: 0
		lineageTag: 8f899730-757e-4c4f-8543-398108c8d584
		summarizeBy: sum
		sourceColumn: Count

		annotation SummarizationSetBy = Automatic

	column link
		dataType: string
		lineageTag: 751b17dc-c397-47a4-96ed-6441a21548e0
		summarizeBy: none
		sourceColumn: link

		annotation SummarizationSetBy = Automatic

	partition word_count = m
		mode: import
		source =
				let
				    Source = related_news,
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"link", "clean_title"}),
				    #"Split Column by Delimiter" = Table.ExpandListColumn(Table.TransformColumns(#"Removed Other Columns", {{"clean_title", Splitter.SplitTextByDelimiter(" ", QuoteStyle.Csv), let itemType = (type nullable text) meta [Serialized.Text = true] in type {itemType}}}), "clean_title"),
				    #"Filtered Rows" = Table.SelectRows(#"Split Column by Delimiter", each [clean_title] <> null and [clean_title] <> ""),
				    #"Grouped Rows" = Table.Group(#"Filtered Rows", {"clean_title", "link"}, {{"Count", each Table.RowCount(_), Int64.Type}})
				in
				    #"Grouped Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

